#include"linkedlist.h"
int main()
{
	//Linked List of integer values 
	Linked_List<int> linked_list_1;
	cout << "Insertion at Tail of Linked List \n\n";
	linked_list_1.insert_At_Tail(1);
	linked_list_1.insert_At_Tail(2);
	linked_list_1.insert_At_Tail(3);
	linked_list_1.insert_At_Tail(4);
	linked_list_1.insert_At_Tail(5);
	linked_list_1.display();
	cout << "\n The value deleted from Linked List Tail is " << linked_list_1.delete_from_Tail() << endl;
	linked_list_1.display();  
	cout << "\n The value deleted from Linked List Tail is " << linked_list_1.delete_from_Tail() << endl;
	linked_list_1.display();  
	cout << "\n The value deleted from Linked List Tail is " << linked_list_1.delete_from_Tail() << endl;
	linked_list_1.display();  
	cout << "\n The value deleted from Linked List Tail is " << linked_list_1.delete_from_Tail() << endl;
	linked_list_1.display();  
	cout << "\n The value deleted from Linked List Tail is " << linked_list_1.delete_from_Tail() << endl;
	linked_list_1.display();
	cout << "\n \nInsertion at Head of Linked List \n\n";
	linked_list_1.insert_At_Head(6);
	linked_list_1.insert_At_Head(7);
	linked_list_1.insert_At_Head(8);
	linked_list_1.insert_At_Head(9);
	linked_list_1.insert_At_Head(10);
	linked_list_1.display();
	cout << "\n The value deleted from Linked List Head is " << linked_list_1.delete_from_Head() << endl;
	linked_list_1.display();											 
	cout << "\n The value deleted from Linked List Head is " << linked_list_1.delete_from_Head() << endl;
	linked_list_1.display();											   
	cout << "\n The value deleted from Linked List Head is " << linked_list_1.delete_from_Head() << endl;
	linked_list_1.display();											   
	cout << "\n The value deleted from Linked List Head is " << linked_list_1.delete_from_Head() << endl;
	linked_list_1.display();											   
	cout << "\n The value deleted from Linked List Head is " << linked_list_1.delete_from_Head() << endl;
	linked_list_1.display();
	cout << endl << endl;
	//Linked List of Characters values 
	Linked_List<char> linked_list_2;
	cout << "Insertion at Tail of Linked List \n\n";
	linked_list_2.insert_At_Tail('a');
	linked_list_2.insert_At_Tail('b');
	linked_list_2.insert_At_Tail('c');
	linked_list_2.insert_At_Tail('d');
	linked_list_2.insert_At_Tail('e');
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Tail is " << linked_list_2.delete_from_Tail() << endl;
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Tail is " << linked_list_2.delete_from_Tail() << endl;
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Tail is " << linked_list_2.delete_from_Tail() << endl;
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Tail is " << linked_list_2.delete_from_Tail() << endl;
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Tail is " << linked_list_2.delete_from_Tail() << endl;
	linked_list_2.display();
	cout << "\n \nInsertion at Head of Linked List \n\n";
	linked_list_2.insert_At_Head('f');
	linked_list_2.insert_At_Head('g');
	linked_list_2.insert_At_Head('h');
	linked_list_2.insert_At_Head('i');
	linked_list_2.insert_At_Head('j');
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Head is " << linked_list_2.delete_from_Head() << endl;
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Head is " << linked_list_2.delete_from_Head() << endl;
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Head is " << linked_list_2.delete_from_Head() << endl;
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Head is " << linked_list_2.delete_from_Head() << endl;
	linked_list_2.display();
	cout << "\n The value deleted from Linked List Head is " << linked_list_2.delete_from_Head() << endl;
	linked_list_2.display();
	cout << "\n";
	return 0;
}